'use client';

import React from 'react';
import Link from 'next/link';

export function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-slate-900 text-slate-300 pt-14 pb-10 border-t border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8">
          {/* Brand Col */}
          <div className="lg:col-span-2 space-y-4">
            <Link href="/" className="flex items-center gap-2.5 font-bold text-xl text-white tracking-tight">
              <div className="w-8 h-8 rounded-xl bg-emerald-600 flex items-center justify-center text-white font-black text-lg">
                M
              </div>
              <span>MoneyPath AI</span>
            </Link>
            <p className="text-sm text-slate-400 max-w-sm leading-relaxed">
              Free educational tools for understanding your money. See your numbers and understand your options through deterministic calculators and clear plain-language explanations.
            </p>
            <div className="text-xs text-slate-500 space-y-1">
              <p>Primary target markets: United States 🇺🇸 & United Kingdom 🇬🇧</p>
              <p>Calculator does the math. AI explains the result.</p>
            </div>
          </div>

          {/* Calculators */}
          <div>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-4">Calculators</h4>
            <ul className="space-y-2.5 text-sm">
              <li>
                <Link href="/tools/debt-payoff-calculator" className="hover:text-emerald-400 transition-colors">
                  Debt Payoff Planner
                </Link>
              </li>
              <li>
                <Link href="/tools/savings-goal-calculator" className="hover:text-emerald-400 transition-colors">
                  Savings Goal Calculator
                </Link>
              </li>
              <li>
                <Link href="/tools/retirement-calculator" className="hover:text-emerald-400 transition-colors">
                  Retirement Growth Estimator
                </Link>
              </li>
            </ul>
          </div>

          {/* Learn & Methodology */}
          <div>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-4">Education & Trust</h4>
            <ul className="space-y-2.5 text-sm">
              <li>
                <Link href="/learn" className="hover:text-emerald-400 transition-colors">
                  Financial Learning Hub
                </Link>
              </li>
              <li>
                <Link href="/methodology" className="hover:text-emerald-400 transition-colors">
                  Calculation Methodology
                </Link>
              </li>
              <li>
                <Link href="/editorial-policy" className="hover:text-emerald-400 transition-colors">
                  Editorial Policy
                </Link>
              </li>
            </ul>
          </div>

          {/* Company & Legal */}
          <div>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-4">Company & Legal</h4>
            <ul className="space-y-2.5 text-sm">
              <li>
                <Link href="/about" className="hover:text-emerald-400 transition-colors">
                  About MoneyPath
                </Link>
              </li>
              <li>
                <Link href="/contact" className="hover:text-emerald-400 transition-colors">
                  Contact Us
                </Link>
              </li>
              <li>
                <Link href="/privacy-policy" className="hover:text-emerald-400 transition-colors">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/financial-disclaimer" className="hover:text-emerald-400 transition-colors">
                  Financial Disclaimer
                </Link>
              </li>
            </ul>
          </div>
        </div>

        {/* Legal Disclaimer Line */}
        <div className="pt-8 border-t border-slate-800 text-xs text-slate-400 leading-relaxed space-y-2">
          <p>
            <strong className="text-slate-300">Regulatory Compliance Notice:</strong> MoneyPath AI provides educational financial software tools and general informative content only. MoneyPath AI is NOT a bank, financial adviser, tax consultant, or investment adviser. Results generated by our calculators are hypothetical scenario estimates produced by deterministic mathematical code based on user inputs.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 text-slate-400 text-xs">
            <p>© {currentYear} MoneyPath AI. All rights reserved.</p>
            <div className="flex items-center gap-6">
              <Link href="/privacy-policy" className="hover:text-slate-200 transition-colors">Privacy</Link>
              <Link href="/financial-disclaimer" className="hover:text-slate-200 transition-colors">Disclaimer</Link>
              <Link href="/methodology" className="hover:text-slate-200 transition-colors">Methodology</Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
